### ISSUE TITLE
Define Flask Application Instance

### ISSUE THREAD

**Issue by MungaSoftwiz** [MungaSoftwiz/LinkedTweet#2]
**Description:** Define the Flask application instance and configure it using environment variables.

**Tasks:**

- [x] Import necessary modules.
- [x] Load environment variables using `dotenv`
- [x] Create the Flask application instance using `create_app`
