### ISSUE TITLE
Configure Database Migrations

### ISSUE THREAD

**Issue by MungaSoftwiz** [MungaSoftwiz/LinkedTweet#3]
**Description:** Set up database migrations using Flask-Migrate.

**Tasks:**

- [ ] Import `Migrate` from `flask_migrate`
- [ ] Initialize `Migrate` with the Flask app and database instance.
- [ ] Ensure schema inclusion in migrations.
